version: '3.8'
services:
  app:
    container_name: poke_app
    build: ./prj
    image: lerab17/poke-api-prj:latest
    command: python app.py
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - ftp
      - redis
  postgres:
    container_name: poke_db
    image: postgres:latest
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgres-admin:
    container_name: poke_db_admin
    image: adminer
    restart: always
    ports:
      - 8080:8080
  ftp: 
    container_name: poke_ftp
    image: delfer/alpine-ftp-server
    restart: always
    expose:
      - 21
    environment:
      - "USERS=${FTP_USER}|${FTP_PASSWORD}|/ftp/ftp"
  redis:
    container_name: poke_cache
    image: redis:7.0.9-alpine
    restart: unless-stopped
    command: redis-server --port "${CACHE_REDIS_PORT}"
    volumes:
      - redis-data:/data
  grafana:
    image: grafana/grafana-enterprise
    container_name: poke_grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgres-data:
  redis-data:
  grafana-data:
