{
 "title": "Pokemons",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "General fight stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM fights LIMIT 50 "
    },
    {
     "rawSql": "SELECT AVG(rounds) FROM fights;"
    }
   ]
  },
  {
   "title": "Top 5 Pokemon by number of wins",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pokemon, COUNT(*) AS wins FROM (SELECT CASE WHEN win = TRUE THEN select_pokemon ELSE vs_pokemon END AS pokemon FROM fights) AS combined GROUP BY pokemon ORDER BY wins DESC, pokemon ASC LIMIT 5;"
    }
   ]
  },
  {
   "title": "Number of fights held by day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT DATE(date_time) AS fight_date, COUNT(*) AS fight_count FROM fights WHERE DATE(date_time) >= CURRENT_DATE - INTERVAL '14 days' GROUP BY fight_date ORDER BY fight_date;"
    }
   ]
  },
  {
   "title": "Number of avg rounds held by day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT DATE(date_time) AS fight_date, AVG(rounds) AS avg_rounds FROM fights WHERE DATE(date_time) >= CURRENT_DATE - INTERVAL '14 days' GROUP BY fight_date ORDER BY fight_date;"
    }
   ]
  }
 ]
}